version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: ./node_modules/.bin/nyc report --reporter=text-lcov
      - store_artifacts:
          path: coverage
          prefix: coverage
