name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["10", "12", "14"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run docker
      - run: npm run smoke
