name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["10", "12", "14"]
        ts-version: ["3.4", "3.5"] # TODO: 3.6, 3.7, 3.8, and 3.9 fail...
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm install typescript@${{ matrix.ts-version }}
      - run: npm test
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run docker
      - run: npm run smoke
